# Main OpenAPI spec
openapi: 3.0.1
info:
  title: LightTrack API
  description: API for the LightTrack task-tracking system.
  version: 1.0.0
servers:
  - url: https://api.lighttrack.com/v1
paths:
  /users:
    $ref: './users.yaml#/paths/~1users'
  /users/{id}:
    $ref: './users.yaml#/paths/~1users~1{id}'
  /groups:
    $ref: './groups.yaml#/paths/~1groups'
  /projects:
    $ref: './projects.yaml#/paths/~1projects'
  /projects/{id}:
    $ref: './projects.yaml#/paths/~1projects~1{id}'
  /epics:
    $ref: './epics.yaml#/paths/~1epics'
  /stories:
    $ref: './stories.yaml#/paths/~1stories'
  /tasks:
    $ref: './tasks.yaml#/paths/~1tasks'
  /tasks/{id}:
    $ref: './tasks.yaml#/paths/~1tasks~1{id}'
  /taskwatchers:
    $ref: './taskwatchers.yaml#/paths/~1taskwatchers'
